# Generated by Django 6.0.3 on 2026-05-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='renewed',
            field=models.BooleanField(default=False),
        ),
    ]
